# Generated by Django 4.2.3 on 2023-09-02 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requestmanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmanagement',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestmanagement',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestmanagement',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requestmanagement.requesttype'),
        ),
    ]
